services:
  cronicle:
    image: bluet/cronicle-docker:0.9.77@sha256:e00ad0cde51ef3212041f1ceaef0ae515f7e2e40b43f4fe1b34e9be84152126c
    container_name: cronicle
    hostname: cronicle
    user: "0:10000"
    environment:
      - TZ=America/Los_Angeles
      - CRONICLE_base_app_url=https://{{{domainForApp "cronicle"}}}
      - CRONICLE_custom_live_log_socket_url=https://{{{domainForApp "cronicle"}}}
      - CRONICLE_universal_web_hook={{{SECRET_CRONICLE_UNIVERSAL_WEB_HOOK}}}
    # ports:
    #   - "3012:3012"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/cronicle/data:/opt/cronicle/data
      - /docker/cronicle/logs:/opt/cronicle/logs
      - /docker/cronicle/plugins:/opt/cronicle/plugins
      - /docker/cronicle/workloads/app:/app
      - ./:/opt/scripts
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider localhost:3012/api/app/ping || exit 1",
        ]
      interval: 5s
      timeout: 1s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.cronicle.rule=Host(`{{{domainForApp "cronicle"}}}`)
      - traefik.http.routers.cronicle.entrypoints=https
      - traefik.http.routers.cronicle.tls=true
      - traefik.http.routers.cronicle.tls.certresolver=porkbun
      - traefik.http.routers.cronicle.service=cronicle
      - traefik.http.services.cronicle.loadbalancer.server.port=3012
    networks:
      - traefik

networks:
  traefik:
    external: true
