id = 200
hostname = "copyparty-pulumi"
enabled = true

description = "copyparty lightweight fileserver container"
tags = ["fileserver", "fileshare"]
services = ["copyparty"]

# [[mountPoints]]
# volume = "/void/documents"
# mountPoint = "/mnt/documents"

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
