id = 200
hostname = "copyparty-pulumi"
enabled = true

description = "copyparty lightweight fileserver container"
tags = ["fileserver", "fileshare"]
services = ["traefik", "copyparty", "mealie"]

[[mountPoints]]
volume = "/void/documents"
mountPoint = "{{{DOCS_MOUNTPOINT}}}"

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
