# verified
id = 200
hostname = "copyparty-pulumi"
enabled = true

description = "copyparty lightweight fileserver container"

[stacks]
traefik = {}
dozzle = {}
copyparty = {}

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 512

[disk]
size = 4

[[mountPoints]]
volume = "/void/audiobooks"
mountPoint = "/mnt/audiobooks"

[[mountPoints]]
volume = "/void/backups"
mountPoint = "/mnt/backups"

[[mountPoints]]
volume = "/void/documents"
mountPoint = "/mnt/documents"

[[mountPoints]]
volume = "/void/drive"
mountPoint = "/mnt/drive"

[[mountPoints]]
volume = "/void/media"
mountPoint = "/mnt/media"

[[mountPoints]]
volume = "/void/photos"
mountPoint = "/mnt/photos"

[[mountPoints]]
volume = "/void/podcasts"
mountPoint = "/mnt/podcasts"

[[mountPoints]]
volume = "/void/restic"
mountPoint = "/mnt/restic"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
