services:
  ytptube:
    user: 0:0
    image: ghcr.io/arabcoders/ytptube:v1.1.0@sha256:76c0aaae2f8e9c07813a0e2e006e4fd48aa7a1bf5c098df31a94a899550842f1
    container_name: ytptube
    restart: unless-stopped
    # ports:
    #   - "8081:8081"
    volumes:
      - /docker/ytptube/config:/config:rw
      - /mnt/media/downloads/ytptube:/downloads:rw
    tmpfs:
      - /tmp
    labels:
      - traefik.enable=true
      - traefik.http.routers.ytptube.rule=Host(`{{{domainForApp "ytptube"}}}`)
      - traefik.http.routers.ytptube.entrypoints=https
      - traefik.http.routers.ytptube.tls=true
      - traefik.http.routers.ytptube.tls.certresolver=porkbun
      - traefik.http.routers.ytptube.service=ytptube
      - traefik.http.services.ytptube.loadbalancer.server.port=8081
    networks:
      - traefik

networks:
  traefik:
    external: true
