services:
  ytptube:
    user: 0:0
    image: ghcr.io/arabcoders/ytptube:v2.0.6@sha256:eb043fe0b0037b6d4998de08ed3499adb1043ebe060d2b675f8382c145b226b3
    container_name: ytptube
    restart: unless-stopped
    # ports:
    #   - "8081:8081"
    volumes:
      - /docker/ytptube/config:/config:rw
      - /mnt/media/downloads/ytptube:/downloads:rw
    tmpfs:
      - /tmp
    labels:
      - traefik.enable=true
      - traefik.http.routers.ytptube.rule=Host(`{{{domainForApp "ytptube"}}}`)
      - traefik.http.routers.ytptube.entrypoints=https
      - traefik.http.routers.ytptube.tls=true
      - traefik.http.routers.ytptube.tls.certresolver=porkbun
      - traefik.http.routers.ytptube.service=ytptube
      - traefik.http.services.ytptube.loadbalancer.server.port=8081
    networks:
      - traefik

networks:
  traefik:
    external: true
