services:
  ytptube:
    user: 0:0
    image: ghcr.io/arabcoders/ytptube:v1.2.8@sha256:a8f1be3c60a8b5284befffb18d1cb5ef4c452f804189875838d99f986ad67448
    container_name: ytptube
    restart: unless-stopped
    # ports:
    #   - "8081:8081"
    volumes:
      - /docker/ytptube/config:/config:rw
      - /mnt/media/downloads/ytptube:/downloads:rw
    tmpfs:
      - /tmp
    labels:
      - traefik.enable=true
      - traefik.http.routers.ytptube.rule=Host(`{{{domainForApp "ytptube"}}}`)
      - traefik.http.routers.ytptube.entrypoints=https
      - traefik.http.routers.ytptube.tls=true
      - traefik.http.routers.ytptube.tls.certresolver=porkbun
      - traefik.http.routers.ytptube.service=ytptube
      - traefik.http.services.ytptube.loadbalancer.server.port=8081
    networks:
      - traefik

networks:
  traefik:
    external: true
