services:
  gatus:
    image: ghcr.io/twin/gatus:v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
    container_name: gatus
    # ports:
    #   - "8080:8080"
    volumes:
      - ./config.yaml:/config/config.yaml:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.gatus.rule=Host(`{{{domainForApp "gatus"}}}`)
      - traefik.http.routers.gatus.entrypoints=https
      - traefik.http.routers.gatus.tls=true
      - traefik.http.routers.gatus.tls.certresolver=porkbun
      - traefik.http.routers.gatus.service=gatus
      - traefik.http.services.gatus.loadbalancer.server.port=8080
    networks:
      - traefik

networks:
  traefik:
    external: true
