id = 213
hostname = "admin-pulumi"
enabled = false

description = "homelab administration-related apps"
tags = ["administration", "ansible"]
services = ["traefik", "semaphore"]

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 8

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
