name: it-tools
services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    # ports:
    #   - 8090:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.ittools.rule=Host(`{{{APP_DOMAIN}}}`)
      - traefik.http.routers.ittools.entrypoints=https
      - traefik.http.routers.ittools.tls=true
      - traefik.http.routers.ittools.tls.certresolver=porkbun
      - traefik.http.routers.ittools.service=ittools
      - traefik.http.services.ittools.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    external: true
