id = 212
hostname = "syncthing-pulumi"
enabled = false

description = "simple file syncing across devices"
stacks = ["traefik", "syncthing"]

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 8

[[mountPoints]]
volume = "/void/documents"
mountPoint = "/mnt/documents"

[[mountPoints]]
volume = "/void/drive"
mountPoint = "/mnt/drive"

[[mountPoints]]
volume = "/void/media"
mountPoint = "/mnt/media"

[[mountPoints]]
volume = "/void/photos"
mountPoint = "/mnt/photos"

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
