services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:10.22.1@sha256:3aa4eb2c52c9f9e22bda450cae3187e1de114581f7850d8136c98164837a406c
    container_name: cyberchef
    # ports:
    #   - 8081:80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.cyberchef.rule=Host(`{{{domainForApp "cyberchef"}}}`)
      - traefik.http.routers.cyberchef.entrypoints=https
      - traefik.http.routers.cyberchef.tls=true
      - traefik.http.routers.cyberchef.tls.certresolver=porkbun
      - traefik.http.routers.cyberchef.service=cyberchef
      - traefik.http.services.cyberchef.loadbalancer.server.port=80
      - traefik.http.routers.cyberchef.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
