packages:
  - "libs/*"

onlyBuiltDependencies:
  - "@pulumi/ansible"
  - "@pulumi/command"
  - "@pulumi/porkbun"
  - esbuild
  - protobufjs

patchedDependencies:
  "@pulumi/command": patches/@pulumi__command.patch
