onlyBuiltDependencies:
  - "@pulumi/ansible"
  - "@pulumi/command"
  - "@pulumi/porkbun"
  - esbuild
  - protobufjs

patchedDependencies:
  "@hanseltime/pulumi-file-utils": patches/@hanseltime__pulumi-file-utils.patch
  "@pulumi/command": patches/@pulumi__command.patch
