services:
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:0.8.1@sha256:6aa18122e08299cf05edf0aa6135d9c97d92839933f5377f8fde59978430e543
    container_name: handbrake-web-server
    user: 0:0
    # ports:
    #   - 9999:9999
    volumes:
      - /docker/handbrake-web/server:/data
      - /mnt/media:/video # ensure this path is the same across all containers
    labels:
      - traefik.enable=true
      - traefik.http.routers.handbrake.rule=Host(`{{{domainForApp "handbrake"}}}`)
      - traefik.http.routers.handbrake.entrypoints=https
      - traefik.http.routers.handbrake.tls=true
      - traefik.http.routers.handbrake.tls.certresolver=porkbun
      - traefik.http.routers.handbrake.service=handbrake
      - traefik.http.services.handbrake.loadbalancer.server.port=9999
    networks:
      - traefik

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:0.7.3@sha256:e4768a28a98002610c3b2d8bb9f3d5a05ba5f87e08c8df9aec2778760b206b45
    container_name: handbrake-web-worker
    user: 0:0
    environment:
      - WORKER_ID=handbrake-worker # give your worker a unique name
      - SERVER_URL=handbrake-server # change if setting up a standalone worker, prefix with http(s):// if necessary
      - SERVER_PORT=9999 # change if using a reverse proxy or the port is otherwise different than above
    volumes:
      - /mnt/media:/video # ensure this path is the same across all containers
    depends_on:
      - handbrake-server

networks:
  traefik:
    external: true
