services:
  mazanoke:
    container_name: mazanoke
    image: ghcr.io/civilblur/mazanoke:v1.1.5@sha256:e43dc48de575b7a032bbefd96b890d69c1f141417e43d5d096469aa1398711d6
    # ports:
    #   - "3474:80"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mazanoke.rule=Host(`{{{domainForApp "mazanoke"}}}`)
      - traefik.http.routers.mazanoke.entrypoints=https
      - traefik.http.routers.mazanoke.tls=true
      - traefik.http.routers.mazanoke.tls.certresolver=porkbun
      - traefik.http.routers.mazanoke.service=mazanoke
      - traefik.http.services.mazanoke.loadbalancer.server.port=80
      - traefik.http.routers.mazanoke.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
