services:
  dozzle:
    image: amir20/dozzle:v11.1.0@sha256:7c4fb7f8124f5dea15ade881535cc19cc9a03e66639fd28154ff43a93b78944b
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - ./users.yaml:/data/users.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 8080:8080
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      # - DOZZLE_AUTH_PROVIDER=simple # uncomment to enable username/pw auth
      - DOZZLE_NO_ANALYTICS
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`{{{domainForApp "dozzle"}}}`)
      - traefik.http.routers.dozzle.entrypoints=https
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.routers.dozzle.tls.certresolver=porkbun
      - traefik.http.routers.dozzle.service=dozzle
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
      - traefik.http.routers.dozzle.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
