services:
  omni-tools:
    image: iib0011/omni-tools:0.5.0@sha256:9d494a4d8d64f34a87ebbf5bc5e1a5f02b5b9796f7ddbc9e3aacda5996e76b61
    container_name: omni-tools
    restart: unless-stopped
    # ports:
    #   - "8080:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.omnitools.rule=Host(`{{{domainForApp "omni-tools"}}}`)
      - traefik.http.routers.omnitools.entrypoints=https
      - traefik.http.routers.omnitools.tls=true
      - traefik.http.routers.omnitools.tls.certresolver=porkbun
      - traefik.http.routers.omnitools.service=omnitools
      - traefik.http.services.omnitools.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    external: true
