services:
  omni-tools:
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    restart: unless-stopped
    # ports:
    #   - "8080:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.omnitools.rule=Host(`{{{domainForApp "omni-tools"}}}`)
      - traefik.http.routers.omnitools.entrypoints=https
      - traefik.http.routers.omnitools.tls=true
      - traefik.http.routers.omnitools.tls.certresolver=porkbun
      - traefik.http.routers.omnitools.service=omnitools
      - traefik.http.services.omnitools.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    external: true
