services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.3@sha256:ef4a44819a60469682c7b5e69183e6401171891feaa60186652d292c59e41b30
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # ports:
    #   - 8081:8081 # qbittorrent web interface
    #   - 6881:6881 # qbittorrent torrent port
    #   - 6789:6789 # nzbget
    #   # - "5030:5030" # slskd http
    #   - "5031:5031" # slskd https
    #   - "50300:50300" # Soulseek
    volumes:
      - /docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY={{{SECRET_WIREGUARD_PRIVATE_KEY}}}
      - WIREGUARD_PRESHARED_KEY={{{SECRET_WIREGUARD_PRESHARED_KEY}}}
      - WIREGUARD_ADDRESSES={{{SECRET_WIREGUARD_ADDRESSES}}}
      - FIREWALL_VPN_INPUT_PORTS=29730
      - SERVER_COUNTRIES=United States
      - HEALTH_VPN_DURATION_INITIAL=120s
    depends_on:
      deunhealth:
        condition: service_started
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.qbittorrent.rule=Host(`{{{domainForApp "qbittorrent"}}}`)
      - traefik.http.routers.qbittorrent.entrypoints=https
      - traefik.http.routers.qbittorrent.tls=true
      - traefik.http.routers.qbittorrent.tls.certresolver=porkbun
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8081
      - traefik.http.routers.qbittorrent.middlewares=oidc-auth@file
      #
      - traefik.tcp.routers.qbittorrent-bittorrent.rule=HostSNI(`*`)
      - traefik.tcp.routers.qbittorrent-bittorrent.entrypoints=qbittorrent-6881-tcp
      - traefik.tcp.routers.qbittorrent-bittorrent.service=qbittorrent-bittorrent
      - traefik.tcp.services.qbittorrent-bittorrent.loadbalancer.server.port=6881
      #
      - traefik.http.routers.nzbget.rule=Host(`{{{domainForApp "nzbget"}}}`)
      - traefik.http.routers.nzbget.entrypoints=https
      - traefik.http.routers.nzbget.tls=true
      - traefik.http.routers.nzbget.tls.certresolver=porkbun
      - traefik.http.routers.nzbget.service=nzbget
      - traefik.http.services.nzbget.loadbalancer.server.port=6789
      - traefik.http.routers.nzbget.middlewares=oidc-auth@file
      #
      - traefik.http.routers.slskd.rule=Host(`{{{domainForApp "slskd"}}}`)
      - traefik.http.routers.slskd.entrypoints=https
      - traefik.http.routers.slskd.tls=true
      - traefik.http.routers.slskd.tls.certresolver=porkbun
      - traefik.http.routers.slskd.service=slskd
      - traefik.http.services.slskd.loadbalancer.server.port=5030
      - traefik.http.routers.slskd.middlewares=oidc-auth@file
      # https://doc.traefik.io/traefik/reference/routing-configuration/tcp/router/rules-and-priority/#hostsni-and-hostsniregexp
      - traefik.tcp.routers.slskd-listen.rule=HostSNI(`*`)
      - traefik.tcp.routers.slskd-listen.entrypoints=slskd-listen-50300-tcp
      - traefik.tcp.routers.slskd-listen.service=slskd-listen
      - traefik.tcp.services.slskd-listen.loadbalancer.server.port=50300
    networks:
      - traefik

  deunhealth:
    image: qmcgaw/deunhealth:latest@sha256:fca3832ace35e3c028d3ec2e6271ac1161ed302b75b34e9dd01db1c106a25802
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ={{{global:TIMEZONE}}}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  apprise:
    image: caronc/apprise:1.2.6@sha256:a92f836b0c2c53523465b670f290615a0ac5c863b0ff72e48fac91c1dac795de
    environment:
      - APPRISE_WORKER_COUNT=1
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_DEFAULT_THEME=dark
      - APPRISE_DEFAULT_CONFIG_ID=homelab
      - APPRISE_CONFIG_LOCK=yes # should not be able to edit through UI
      - PGID=0
      - PUID=0
    volumes:
      - /docker/apprise/attach:/attach
      - /docker/apprise/plugin:/plugin
      - ./config:/config
    restart: unless-stopped
    # ports:
    #   - 8000:8000
    container_name: apprise
    labels:
      - traefik.enable=true
      - traefik.http.routers.apprise.rule=Host(`{{{domainForApp "apprise"}}}`)
      - traefik.http.routers.apprise.entrypoints=https
      - traefik.http.routers.apprise.tls=true
      - traefik.http.routers.apprise.tls.certresolver=porkbun
      - traefik.http.routers.apprise.service=apprise
      - traefik.http.services.apprise.loadbalancer.server.port=8000
      - traefik.http.routers.apprise.middlewares=oidc-auth@file
    networks:
      - traefik

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:5.1.2@sha256:7034f73a3c6fa4ea40fd67df462939d1665d765231b572523921c98c2db5362e
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      - PUID=0
      - PGID=0
      - TZ={{{global:TIMEZONE}}}
      - WEBUI_PORT=8081
      - TORRENTING_PORT=29730
    volumes:
      - /docker/qbittorrent:/config
      - /mnt/media:/data
    network_mode: service:gluetun
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  nzbget:
    image: ghcr.io/linuxserver/nzbget:25.4.20251114@sha256:92be8b940db9c185947e940b5abb93551ce4a8be15b8254167fe26e969a3fc99
    container_name: nzbget
    environment:
      - PUID=0
      - PGID=0
      - TZ={{{global:TIMEZONE}}}
    volumes:
      - /docker/nzbget:/config
      - /mnt/media:/data
    restart: unless-stopped
    network_mode: service:gluetun
    labels:
      - deunhealth.restart.on.unhealthy=true
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://127.0.0.1:6789/
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 15s

  slskd:
    image: slskd/slskd:0.24.1@sha256:e3635858d9614a2fb811601afca706dbf97a6838b849905c27294cbce71be268
    container_name: slskd
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    network_mode: service:gluetun
    labels:
      - deunhealth.restart.on.unhealthy=true
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - /docker/slskd/data:/app/data
      - /docker/slskd/incomplete:/app/incomplete
      - /docker/slskd/scripts:/app/scripts
      - /mnt/media:/data
      - ./config/slskd.yml:/app/slskd.yml
    restart: always

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:2.1.5@sha256:643220338204525524db787ff38a607261597f49d1f550694acdb3e908e2b43e
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ={{{global:TIMEZONE}}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/prowlarr:/config
    restart: unless-stopped
    # ports:
    #   - 9696:9696
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://localhost:9696/ping
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 15s
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.prowlarr.rule=Host(`{{{domainForApp "prowlarr"}}}`)
      - traefik.http.routers.prowlarr.entrypoints=https
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.tls.certresolver=porkbun
      - traefik.http.routers.prowlarr.service=prowlarr
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr.middlewares=oidc-auth@file
    networks:
      - traefik

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.16@sha256:60e5edcac39172294ad22d55d1b08c2c0a9fe658cad2f2c4d742ae017d7874de
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ={{{global:TIMEZONE}}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/sonarr:/config
      - /mnt/media:/data
    # ports:
    #   - 8989:8989
    depends_on:
      qbittorrent:
        condition: service_healthy
        restart: true
      nzbget:
        condition: service_healthy
        restart: true
      prowlarr:
        condition: service_healthy
        restart: true
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://localhost:8989/ping
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 5s
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.sonarr.rule=Host(`{{{domainForApp "sonarr"}}}`)
      - traefik.http.routers.sonarr.entrypoints=https
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.tls.certresolver=porkbun
      - traefik.http.routers.sonarr.service=sonarr
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.middlewares=oidc-auth@file
    networks:
      - traefik

  radarr:
    image: ghcr.io/linuxserver/radarr:5.28.0@sha256:c984533510abe0219a70e80d15bd0d212b7df21baa0913759c4ce6cc9092240b
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ={{{global:TIMEZONE}}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/radarr:/config
      - /mnt/media:/data
    # ports:
    #   - 7878:7878
    depends_on:
      qbittorrent:
        condition: service_healthy
        restart: true
      nzbget:
        condition: service_healthy
        restart: true
      prowlarr:
        condition: service_healthy
        restart: true
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://localhost:7878/ping
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 5s
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.radarr.rule=Host(`{{{domainForApp "radarr"}}}`)
      - traefik.http.routers.radarr.entrypoints=https
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=porkbun
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.middlewares=oidc-auth@file
    networks:
      - traefik

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:pr-plugins-3.1.1.4884@sha256:64d2979d6bb54d3b7ff413faa3ebbe81d71643f6bbc920e364b102782b718cdc
    restart: unless-stopped
    depends_on:
      qbittorrent:
        condition: service_healthy
        restart: true
      nzbget:
        condition: service_healthy
        restart: true
      prowlarr:
        condition: service_healthy
        restart: true
    environment:
      - PUID=0
      - PGID=0
      - TZ={{{global:TIMEZONE}}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/lidarr:/config
      - /mnt/media:/data
    # ports:
    #   - 8686:8686
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://localhost:8686/ping
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 5s
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.lidarr.rule=Host(`{{{domainForApp "lidarr"}}}`)
      - traefik.http.routers.lidarr.entrypoints=https
      - traefik.http.routers.lidarr.tls=true
      - traefik.http.routers.lidarr.tls.certresolver=porkbun
      - traefik.http.routers.lidarr.service=lidarr
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - traefik.http.routers.lidarr.middlewares=oidc-auth@file
    networks:
      - traefik

  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.5.3@sha256:2be164c02c0bb311b6c32e57d3d0ddc2813d524e89ab51a3408c1bf6fafecda5
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ={{{global:TIMEZONE}}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/bazarr:/config
      - /mnt/media:/data
    # ports:
    #   - 6767:6767
    depends_on:
      sonarr:
        condition: service_healthy
        restart: true
      radarr:
        condition: service_healthy
        restart: true
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://127.0.0.1:6767
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 15s
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.bazarr.rule=Host(`{{{domainForApp "bazarr"}}}`)
      - traefik.http.routers.bazarr.entrypoints=https
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.tls.certresolver=porkbun
      - traefik.http.routers.bazarr.service=bazarr
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - traefik.http.routers.bazarr.middlewares=oidc-auth@file
    networks:
      - traefik

  subsyncarr:
    image: mrorbitman/subsyncarr:0.0.8@sha256:5185ff4d403e1267fc38a30dcf13c631ebf4ff0e56a8bbb1dc1da70996bf2b83
    container_name: subsyncarr
    user: 0:0
    # run every 30 minutes (1800 seconds). workaround since builtin cron functionality doesn't work
    command: "sh -c 'set -x && while true; do /app/startup.sh & sleep 1800 && killall startup.sh tail; done'"
    volumes:
      - /mnt/media/movies:/movies
      - /mnt/media/tv:/tv
    restart: unless-stopped
    environment:
      - TZ={{{global:TIMEZONE}}}
      - SCAN_PATHS=/movies,/tv # Remember to mount these as volumes. Must begin with /. Default value is '/scan_dir'
      # - EXCLUDE_PATHS=/movies/temp,/tv/downloads # Exclude certain sub-directories from the scan
      - MAX_CONCURRENT_SYNC_TASKS=1 # Defaults to 1 if not set. Higher number will consume more CPU but sync your library faster
      - INCLUDE_ENGINES=ffsubsync,autosubsync # If not set, all engines are used by default

  profilarr:
    image: santiagosayshey/profilarr:v1.1.3@sha256:c8ad91a8e5d60b3816321b3a1f68332b29a23f910f6bd2c2d7b4a83f881f032f
    container_name: profilarr
    user: 0:0
    # ports:
    #   - 6868:6868
    volumes:
      - /docker/profilarr:/config
    environment:
      - TZ={{{global:TIMEZONE}}}
    restart: unless-stopped
    depends_on:
      sonarr:
        condition: service_healthy
        restart: true
      radarr:
        condition: service_healthy
        restart: true
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.profilarr.rule=Host(`{{{domainForApp "profilarr"}}}`)
      - traefik.http.routers.profilarr.entrypoints=https
      - traefik.http.routers.profilarr.tls=true
      - traefik.http.routers.profilarr.tls.certresolver=porkbun
      - traefik.http.routers.profilarr.service=profilarr
      - traefik.http.services.profilarr.loadbalancer.server.port=6868
      - traefik.http.routers.profilarr.middlewares=oidc-auth@file
    networks:
      - traefik
    # healthcheck:
    #   test:
    #     - CMD
    #     - wget
    #     - --quiet
    #     - --timeout=3
    #     - --tries=1
    #     - --spider
    #     - http://127.0.0.1:6868
    #   interval: 5s
    #   timeout: 4s
    #   retries: 4
    #   start_period: 5s

  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:2.4.5@sha256:d7e974bc88c06c6bf23cb2cb4451bdfd012bb32866d4aca143617704758949ab
    container_name: cleanuparr
    restart: unless-stopped
    depends_on:
      sonarr:
        condition: service_healthy
        restart: true
      radarr:
        condition: service_healthy
        restart: true
      lidarr:
        condition: service_healthy
        restart: true
      qbittorrent:
        condition: service_healthy
        restart: true
      nzbget:
        condition: service_healthy
        restart: true
    # ports:
    #   - 11011:11011
    volumes:
      - /docker/cleanuparr:/config
      - /mnt/media:/data
    # https://cleanuparr.github.io/Cleanuparr/docs/installation/detailed#environment-variables
    environment:
      - PORT=11011
      - BASE_PATH=
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ={{{global:TIMEZONE}}}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11011/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.cleanuparr.rule=Host(`{{{domainForApp "cleanuparr"}}}`)
      - traefik.http.routers.cleanuparr.entrypoints=https
      - traefik.http.routers.cleanuparr.tls=true
      - traefik.http.routers.cleanuparr.tls.certresolver=porkbun
      - traefik.http.routers.cleanuparr.service=cleanuparr
      - traefik.http.services.cleanuparr.loadbalancer.server.port=11011
      - traefik.http.routers.cleanuparr.middlewares=oidc-auth@file
    networks:
      - traefik

  huntarr:
    image: huntarr/huntarr:8.2.10@sha256:b5a47c2b43806165f433d308d69a21e74a687ce59f4fcccb612d6a7acb3af6d7
    container_name: huntarr
    restart: unless-stopped
    # ports:
    #   - "9705:9705"
    depends_on:
      sonarr:
        condition: service_healthy
        restart: true
      radarr:
        condition: service_healthy
        restart: true
      lidarr:
        condition: service_healthy
        restart: true
      qbittorrent:
        condition: service_healthy
        restart: true
      nzbget:
        condition: service_healthy
        restart: true
    volumes:
      - /docker/huntarr:/config
    environment:
      - TZ={{{global:TIMEZONE}}}
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.huntarr.rule=Host(`{{{domainForApp "huntarr"}}}`)
      - traefik.http.routers.huntarr.entrypoints=https
      - traefik.http.routers.huntarr.tls=true
      - traefik.http.routers.huntarr.tls.certresolver=porkbun
      - traefik.http.routers.huntarr.service=huntarr
      - traefik.http.services.huntarr.loadbalancer.server.port=9705
      - traefik.http.routers.huntarr.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
