services:
  your_spotify:
    image: ghcr.io/linuxserver/your_spotify:1.14.0@sha256:6003b0ab74e36645b0bd17365d05b7311cf8f8698eef0d0956a769bebfbe239e
    container_name: your_spotify
    environment:
      # cannot use root user for this image
      - PUID=1000
      - PGID=1000
      - TZ={{{global:TIMEZONE}}}
      - APP_URL=https://{{{domainForApp "your-spotify"}}}
      - SPOTIFY_PUBLIC={{{SECRET_SPOTIFY_CLIENT_ID}}}
      - SPOTIFY_SECRET={{{SECRET_SPOTIFY_CLIENT_SECRET}}}
      - CORS=all # <APP_URL>:80,<APP_URL>:443 # all
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
    # ports:
    #   - 80:80
    #   - 443:443
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.yourspotify.rule=Host(`{{{domainForApp "your-spotify"}}}`)
      - traefik.http.routers.yourspotify.entrypoints=https
      - traefik.http.routers.yourspotify.tls=true
      - traefik.http.routers.yourspotify.tls.certresolver=porkbun
      - traefik.http.routers.yourspotify.service=yourspotify
      - traefik.http.services.yourspotify.loadbalancer.server.port=80
    networks:
      - your_spotify
      - traefik

  mongo:
    container_name: mongo
    # pinned
    image: mongo:6@sha256:16118486b1c7e672a0d9a1e7f59e3a510eeb0038629ceb678eb43f8029eb77d6
    volumes:
      - /docker/your_spotify/db:/data/db
    restart: unless-stopped
    networks:
      - your_spotify

networks:
  your_spotify:
  traefik:
    external: true
