services:
  server:
    image: yooooomi/your_spotify_server:1.14.0@sha256:73a67b06ad9566ee7df6138dce56358cdea499d8c7fa4aedc8f1d1bc8a9baada
    container_name: your-spotify-api
    restart: always
    # ports:
    #   - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://{{{domainForApp "your-spotify-api"}}} # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: https://{{{domainForApp "your-spotify"}}}
      SPOTIFY_PUBLIC: "{{{SECRET_SPOTIFY_CLIENT_ID}}}"
      SPOTIFY_SECRET: "{{{SECRET_SPOTIFY_CLIENT_SECRET}}}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.yourspotifyserver.rule=Host(`{{{domainForApp "your-spotify-api"}}}`)
      - traefik.http.routers.yourspotifyserver.entrypoints=https
      - traefik.http.routers.yourspotifyserver.tls=true
      - traefik.http.routers.yourspotifyserver.tls.certresolver=porkbun
      - traefik.http.routers.yourspotifyserver.service=yourspotifyserver
      - traefik.http.services.yourspotifyserver.loadbalancer.server.port=8080
    networks:
      - your_spotify
      - traefik

  mongo:
    container_name: mongo
    # pinned
    image: mongo:6@sha256:16118486b1c7e672a0d9a1e7f59e3a510eeb0038629ceb678eb43f8029eb77d6
    restart: always
    volumes:
      - /docker/your_spotify/db:/data/db
    networks:
      - your_spotify

  web:
    image: yooooomi/your_spotify_client:1.15.0@sha256:46a6fad7df40858b87bf5ac80efb8ff4d604aa63683245d21f6fdfcb0ea083e5
    container_name: your-spotify-web
    restart: always
    # ports:
    #   - "3000:3000"
    environment:
      API_ENDPOINT: https://{{{domainForApp "your-spotify-api"}}}
    labels:
      - traefik.enable=true
      - traefik.http.routers.yourspotifyclient.rule=Host(`{{{domainForApp "your-spotify"}}}`)
      - traefik.http.routers.yourspotifyclient.entrypoints=https
      - traefik.http.routers.yourspotifyclient.tls=true
      - traefik.http.routers.yourspotifyclient.tls.certresolver=porkbun
      - traefik.http.routers.yourspotifyclient.service=yourspotifyclient
      - traefik.http.services.yourspotifyclient.loadbalancer.server.port=3000
    networks:
      - your_spotify
      - traefik

networks:
  your_spotify:
  traefik:
    external: true
