services:
  server:
    image: yooooomi/your_spotify_server:1.15.0@sha256:3679ea122e2083703a3f8c1199acf4b1bb81c81da33334bdcaf478bfbbf36e9b
    container_name: your-spotify-api
    restart: always
    # ports:
    #   - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://{{{domainForApp "your-spotify-api"}}} # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: https://{{{domainForApp "your-spotify"}}}
      SPOTIFY_PUBLIC: "{{{SECRET_SPOTIFY_CLIENT_ID}}}"
      SPOTIFY_SECRET: "{{{SECRET_SPOTIFY_CLIENT_SECRET}}}"
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins
    labels:
      - traefik.enable=true
      - traefik.http.routers.yourspotifyserver.rule=Host(`{{{domainForApp "your-spotify-api"}}}`)
      - traefik.http.routers.yourspotifyserver.entrypoints=https
      - traefik.http.routers.yourspotifyserver.tls=true
      - traefik.http.routers.yourspotifyserver.tls.certresolver=porkbun
      - traefik.http.routers.yourspotifyserver.service=yourspotifyserver
      - traefik.http.services.yourspotifyserver.loadbalancer.server.port=8080
    networks:
      - your_spotify
      - traefik

  mongo:
    container_name: mongo
    # pinned
    image: mongo:6@sha256:16118486b1c7e672a0d9a1e7f59e3a510eeb0038629ceb678eb43f8029eb77d6
    restart: always
    volumes:
      - /docker/your_spotify/db:/data/db
    networks:
      - your_spotify

  web:
    image: yooooomi/your_spotify_client:1.16.0@sha256:848cfed544bb41154001f2d15041103e4c7bcae1d935ca21242e95f727df1cfe
    container_name: your-spotify-web
    restart: always
    # ports:
    #   - "3000:3000"
    environment:
      API_ENDPOINT: https://{{{domainForApp "your-spotify-api"}}}
    labels:
      - traefik.enable=true
      - traefik.http.routers.yourspotifyclient.rule=Host(`{{{domainForApp "your-spotify"}}}`)
      - traefik.http.routers.yourspotifyclient.entrypoints=https
      - traefik.http.routers.yourspotifyclient.tls=true
      - traefik.http.routers.yourspotifyclient.tls.certresolver=porkbun
      - traefik.http.routers.yourspotifyclient.service=yourspotifyclient
      - traefik.http.services.yourspotifyclient.loadbalancer.server.port=3000
      - traefik.http.routers.yourspotifyclient.middlewares=oidc-auth@file
    networks:
      - your_spotify
      - traefik

networks:
  your_spotify:
  traefik:
    external: true
