id = 216
hostname = "cronicle-pulumi"
enabled = true

description = "Cronicle backup worker container"
tags = ["backup"]
services = ["traefik", "cronicle", "mealie"]

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
