services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:2.3.1@sha256:04a473de1f92d4623e87eec5cf95d2aab2d35742ce398f4f514a663cae995ee6
    # ports:
    #   - 3000:3000
    volumes:
      - /docker/docuseal:/data/docuseal
    environment:
      - FORCE_SSL={{{domainForApp "docuseal"}}}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.docuseal.rule=Host(`{{{domainForApp "docuseal"}}}`)
      - traefik.http.routers.docuseal.entrypoints=https
      - traefik.http.routers.docuseal.tls=true
      - traefik.http.routers.docuseal.tls.certresolver=porkbun
      - traefik.http.routers.docuseal.service=docuseal
      - traefik.http.services.docuseal.loadbalancer.server.port=3000
      - traefik.http.routers.docuseal.middlewares=oidc-auth@file
    networks:
      - docuseal
      - traefik

  postgres:
    # pinned
    image: postgres:15@sha256:08155957f670000953ad9bf7f654a13bb0d4fb01b8f1cc83736f2fd18601aab4
    volumes:
      - /docker/docuseal/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - docuseal

networks:
  docuseal:
  traefik:
    external: true
