services:
  metube:
    image: ghcr.io/alexta69/metube:2026.06.20@sha256:a07754cef9632f59d947f5dc0833e8e085476e5e2e999966216453139257db3e
    container_name: metube
    restart: unless-stopped
    # ports:
    #   - "8081:8081"
    volumes:
      - /mnt/media/downloads/metube:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.metube.rule=Host(`{{{domainForApp "metube"}}}`)
      - traefik.http.routers.metube.entrypoints=https
      - traefik.http.routers.metube.tls=true
      - traefik.http.routers.metube.tls.certresolver=porkbun
      - traefik.http.routers.metube.service=metube
      - traefik.http.services.metube.loadbalancer.server.port=8081
    networks:
      - traefik

networks:
  traefik:
    external: true
