services:
  metube:
    image: ghcr.io/alexta69/metube:2026.03.15@sha256:37e2b858622b6f9d8892875cc4669875539788413d0a024b09ab180d428fcb3a
    container_name: metube
    restart: unless-stopped
    # ports:
    #   - "8081:8081"
    volumes:
      - /mnt/media/downloads/metube:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.metube.rule=Host(`{{{domainForApp "metube"}}}`)
      - traefik.http.routers.metube.entrypoints=https
      - traefik.http.routers.metube.tls=true
      - traefik.http.routers.metube.tls.certresolver=porkbun
      - traefik.http.routers.metube.service=metube
      - traefik.http.services.metube.loadbalancer.server.port=8081
    networks:
      - traefik

networks:
  traefik:
    external: true
