services:
  metube:
    image: ghcr.io/alexta69/metube:2026.03.21@sha256:afd3fa2b229e3e6d4c8750618fe148af33a1f70b32af4441ecbd2d08f29d8221
    container_name: metube
    restart: unless-stopped
    # ports:
    #   - "8081:8081"
    volumes:
      - /mnt/media/downloads/metube:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.metube.rule=Host(`{{{domainForApp "metube"}}}`)
      - traefik.http.routers.metube.entrypoints=https
      - traefik.http.routers.metube.tls=true
      - traefik.http.routers.metube.tls.certresolver=porkbun
      - traefik.http.routers.metube.service=metube
      - traefik.http.services.metube.loadbalancer.server.port=8081
    networks:
      - traefik

networks:
  traefik:
    external: true
