services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.3@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
    container_name: homepage
    # ports:
    #   - 3000:3000
    volumes:
      - /docker/homepage:/app/config
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`{{{domainForApp "homepage"}}}`)
      - traefik.http.routers.homepage.entrypoints=https
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=porkbun
      - traefik.http.routers.homepage.service=homepage
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.http.routers.homepage.middlewares=oidc-auth@file
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
