services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.11.0@sha256:b129cb0f674bd6d204e215bde2c2fc3f11d6ad0e82f6d20007cf80f74e1acbb1
    container_name: homepage
    # ports:
    #   - 3000:3000
    volumes:
      - /docker/homepage:/app/config
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`{{{domainForApp "homepage"}}}`)
      - traefik.http.routers.homepage.entrypoints=https
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=porkbun
      - traefik.http.routers.homepage.service=homepage
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.http.routers.homepage.middlewares=oidc-auth@file
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
