services:
  dagu:
    image: ghcr.io/dagu-org/dagu:2.1.3@sha256:bfffcc5c5cb37035e2b2660bcaf0795e171e97c6538da8447964767f92d58034
    container_name: dagu
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    environment:
      - DAGU_TZ={{{global:TIMEZONE}}}
      - DAGU_PORT=8080 # optional. default is 8080
      - DAGU_HOME=/dagu # optional.
      - PUID=0 # optional. default is 1000
      - PGID=0 # optional. default is 1000
    volumes:
      - /docker/dagu:/dagu
      - /root/.ssh:/root/.ssh
      - /root/.ssh:/home/dagu/.ssh
      - ./dags:/dagu/dags
    labels:
      - traefik.enable=true
      - traefik.http.routers.dagu.rule=Host(`{{{domainForApp "dagu"}}}`)
      - traefik.http.routers.dagu.entrypoints=https
      - traefik.http.routers.dagu.tls=true
      - traefik.http.routers.dagu.tls.certresolver=porkbun
      - traefik.http.routers.dagu.service=dagu
      - traefik.http.services.dagu.loadbalancer.server.port=8080
      - traefik.http.routers.dagu.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
