services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:4.5.0@sha256:1277c83dc626853ac14658c1b0aaf003e1bced213c37370d149fdd9622b5747f
    # ports:
    #   - "8282:80/tcp"
    environment:
      TZ: "{{{global:TIMEZONE}}}"
    volumes:
      - /docker/wallos/db:/var/www/html/db
      - /docker/wallos/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.wallos.rule=Host(`{{{domainForApp "wallos"}}}`)
      - traefik.http.routers.wallos.entrypoints=https
      - traefik.http.routers.wallos.tls=true
      - traefik.http.routers.wallos.tls.certresolver=porkbun
      - traefik.http.routers.wallos.service=wallos
      - traefik.http.services.wallos.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    external: true
