services:
  workout-tracker:
    image: ghcr.io/jovandeginste/workout-tracker:master
    container_name: wt-app
    restart: unless-stopped
    # ports:
    #   - 8080:8080
    volumes:
      - /docker/workout-tracker:/data
    environment:
      - WT_JWT_ENCRYPTION_KEY={{{SECRET_JWT_KEY}}}
    labels:
      - traefik.enable=true
      - traefik.http.routers.workouttracker.rule=Host(`{{{domainForApp "workout-tracker"}}}`)
      - traefik.http.routers.workouttracker.entrypoints=https
      - traefik.http.routers.workouttracker.tls=true
      - traefik.http.routers.workouttracker.tls.certresolver=porkbun
      - traefik.http.routers.workouttracker.service=workouttracker
      - traefik.http.services.workouttracker.loadbalancer.server.port=8080
    networks:
      - traefik

networks:
  traefik:
    external: true
