id = 208
hostname = "tools-pulumi"
enabled = true

description = "private image server"
tags = ["tools"]
services = [
    "traefik",
    "cyberchef",
    "docuseal",
    "it-tools",
    "mazanoke",
    "omni-tools",
    "stirling-pdf",
]

[cpu]
cores = 4

[memory]
dedicated = 8192
swap = 4096

[disk]
size = 32

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
