services:
  database:
    image: postgres:15@sha256:24d6c206bba8c0440bceb24a8d4bf642f60bf7aea94887051ea5761d29c22323
    pull_policy: always
    restart: always
    container_name: database
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_PASSWORD: "{{{SECRET_POSTGRES_PASSWORD}}}"
    volumes:
      - /docker/cleanslate/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cleanslate

  graphql-server:
    image: ghcr.io/successible/cleanslate/graphql-server:v4.7.0@sha256:994f6975342d92a487750ac256c4cc3064b2213c470bd021c8edbfd2088a1a69
    pull_policy: always
    restart: always
    container_name: graphql-server
    # ports:
    #   - 8080:8080
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "{{{SECRET_HASURA_GRAPHQL_ADMIN_SECRET}}}"
      HASURA_GRAPHQL_CORS_DOMAIN: https://{{{domainForApp "cleanslate"}}}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:{{{SECRET_POSTGRES_PASSWORD}}}@database:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: false
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: "{{{SECRET_HASURA_GRAPHQL_JWT_SECRET}}}"
    depends_on:
      database:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      # API routes (v1, v2)
      - traefik.http.routers.cleanslate-api.rule=Host(`{{{domainForApp "cleanslate"}}}`) && (PathPrefix(`/v1`) || PathPrefix(`/v2`))
      - traefik.http.routers.cleanslate-api.entrypoints=https
      - traefik.http.routers.cleanslate-api.tls=true
      - traefik.http.routers.cleanslate-api.tls.certresolver=porkbun
      - traefik.http.routers.cleanslate-api.priority=30
      - traefik.http.routers.cleanslate-api.middlewares=cleanslate-security-headers,cleanslate-remove-hasura-role
      - traefik.http.routers.cleanslate-api.service=cleanslate-graphql
      # Console routes
      - traefik.http.routers.cleanslate-console.rule=Host(`{{{domainForApp "cleanslate"}}}`) && PathPrefix(`/console`)
      - traefik.http.routers.cleanslate-console.entrypoints=https
      - traefik.http.routers.cleanslate-console.tls=true
      - traefik.http.routers.cleanslate-console.tls.certresolver=porkbun
      - traefik.http.routers.cleanslate-console.priority=30
      - traefik.http.routers.cleanslate-console.middlewares=cleanslate-console-headers,cleanslate-remove-hasura-role
      - traefik.http.routers.cleanslate-console.service=cleanslate-graphql
      # Health check route
      - traefik.http.routers.cleanslate-health.rule=Host(`{{{domainForApp "cleanslate"}}}`) && Path(`/healthz`)
      - traefik.http.routers.cleanslate-health.entrypoints=https
      - traefik.http.routers.cleanslate-health.tls=true
      - traefik.http.routers.cleanslate-health.tls.certresolver=porkbun
      - traefik.http.routers.cleanslate-health.priority=30
      - traefik.http.routers.cleanslate-health.middlewares=cleanslate-security-headers,cleanslate-remove-hasura-role
      - traefik.http.routers.cleanslate-health.service=cleanslate-graphql
      # Service definition
      - traefik.http.services.cleanslate-graphql.loadbalancer.server.port=8080
      - traefik.http.services.cleanslate-graphql.loadbalancer.passhostheader=true
    networks:
      - traefik
      - cleanslate

  authentication-server:
    image: ghcr.io/successible/cleanslate/authentication-server:v4.7.0@sha256:b73486627a0ef300725016c3b4f33d17e73e458802be146bf2c5e8fb2044252e
    pull_policy: always
    restart: always
    container_name: authentication-server
    # ports:
    #   - 3001:3001
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "{{{SECRET_HASURA_GRAPHQL_ADMIN_SECRET}}}"
      JWT_SIGNING_SECRET: "{{{SECRET_JWT_SIGNING_SECRET}}}"
      NEXT_PUBLIC_USE_FIREBASE: false
    depends_on:
      - database
      - graphql-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Auth routes
      - traefik.http.routers.cleanslate-auth.rule=Host(`{{{domainForApp "cleanslate"}}}`) && PathPrefix(`/auth`)
      - traefik.http.routers.cleanslate-auth.entrypoints=https
      - traefik.http.routers.cleanslate-auth.tls=true
      - traefik.http.routers.cleanslate-auth.tls.certresolver=porkbun
      - traefik.http.routers.cleanslate-auth.priority=30
      - traefik.http.routers.cleanslate-auth.middlewares=cleanslate-security-headers,cleanslate-remove-hasura-role
      - traefik.http.routers.cleanslate-auth.service=cleanslate-auth
      # Service definition
      - traefik.http.services.cleanslate-auth.loadbalancer.server.port=3001
      - traefik.http.services.cleanslate-auth.loadbalancer.passhostheader=true
    networks:
      - traefik
      - cleanslate

  client:
    image: ghcr.io/successible/cleanslate/client:v4.8.0@sha256:8fb5138dcb57358905cc6fd619fcccbf9a787c7a58c2efc0be1c9efb4737b27e
    pull_policy: always
    restart: always
    container_name: client
    # ports:
    #   - 3000:3000
    depends_on:
      - database
      - graphql-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Static files / catch-all route (lowest priority)
      - traefik.http.routers.cleanslate.rule=Host(`{{{domainForApp "cleanslate"}}}`)
      - traefik.http.routers.cleanslate.entrypoints=https
      - traefik.http.routers.cleanslate.tls=true
      - traefik.http.routers.cleanslate.tls.certresolver=porkbun
      - traefik.http.routers.cleanslate.priority=10
      - traefik.http.routers.cleanslate.middlewares=cleanslate-security-headers,cleanslate-remove-hasura-role
      - traefik.http.routers.cleanslate.service=cleanslate
      - traefik.http.services.cleanslate.loadbalancer.server.port=3000
      - traefik.http.services.cleanslate.loadbalancer.passhostheader=true

      # Middleware: Security headers (applied to all routes except console)
      - traefik.http.middlewares.cleanslate-security-headers.headers.referrerPolicy=strict-origin
      - traefik.http.middlewares.cleanslate-security-headers.headers.stsSeconds=31536000
      - traefik.http.middlewares.cleanslate-security-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.cleanslate-security-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.cleanslate-security-headers.headers.frameDeny=true
      - traefik.http.middlewares.cleanslate-security-headers.headers.browserXssFilter=false
      - traefik.http.middlewares.cleanslate-security-headers.headers.contentSecurityPolicy=default-src 'self'; script-src 'self' 'wasm-unsafe-eval' https://apis.google.com https://www.google.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' *.ingest.sentry.io https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://apis.google.com https://world.openfoodfacts.org; frame-src 'self' *.firebaseapp.com https://www.google.com; img-src 'self' https://www.gstatic.com data:; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com; worker-src 'self'; object-src 'none';
      - traefik.http.middlewares.cleanslate-security-headers.headers.permissionsPolicy=accelerometer=(self), autoplay=(self), camera=(self), cross-origin-isolated=(self), display-capture=(self), encrypted-media=(self), fullscreen=(self), geolocation=(self), gyroscope=(self), keyboard-map=(self), magnetometer=(self), microphone=(self), midi=(self), payment=(self), picture-in-picture=(self), publickey-credentials-get=(self), screen-wake-lock=(self), sync-xhr=(self), usb=(self), xr-spatial-tracking=(self)

      # Middleware: Console headers (security headers without CSP)
      - traefik.http.middlewares.cleanslate-console-headers.headers.referrerPolicy=strict-origin
      - traefik.http.middlewares.cleanslate-console-headers.headers.stsSeconds=31536000
      - traefik.http.middlewares.cleanslate-console-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.cleanslate-console-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.cleanslate-console-headers.headers.frameDeny=true
      - traefik.http.middlewares.cleanslate-console-headers.headers.browserXssFilter=false
      - traefik.http.middlewares.cleanslate-console-headers.headers.permissionsPolicy=accelerometer=(self), autoplay=(self), camera=(self), cross-origin-isolated=(self), display-capture=(self), encrypted-media=(self), fullscreen=(self), geolocation=(self), gyroscope=(self), keyboard-map=(self), magnetometer=(self), microphone=(self), midi=(self), payment=(self), picture-in-picture=(self), publickey-credentials-get=(self), screen-wake-lock=(self), sync-xhr=(self), usb=(self), xr-spatial-tracking=(self)

      # Middleware: Remove X-Hasura-Role header from requests
      - traefik.http.middlewares.cleanslate-remove-hasura-role.headers.customRequestHeaders.X-Hasura-Role=
    networks:
      - traefik
      - cleanslate

networks:
  traefik:
    external: true
  cleanslate:

# Caddyfile reference
# $DOMAIN {
# 	header /* {
# 		Referrer-Policy "strict-origin"
# 		Strict-Transport-Security "max-age=31536000; includeSubDomains;"
# 		X-Content-Type-Options "nosniff"
# 		X-Frame-Options "DENY"
# 		X-XSS-Protection "0"
# 		Content-Security-Policy "default-src 'self'; script-src 'self' 'wasm-unsafe-eval' https://apis.google.com https://www.google.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' *.ingest.sentry.io https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://apis.google.com https://world.openfoodfacts.org; frame-src 'self' *.firebaseapp.com https://www.google.com; img-src 'self' https://www.gstatic.com data:; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com; worker-src 'self'; object-src 'none';"
# 		Permissions-Policy "accelerometer=(self), autoplay=(self), camera=(self), cross-origin-isolated=(self), display-capture=(self), encrypted-media=(self), fullscreen=(self), geolocation=(self), gyroscope=(self), keyboard-map=(self), magnetometer=(self), microphone=(self), midi=(self), payment=(self), picture-in-picture=(self), publickey-credentials-get=(self), screen-wake-lock=(self), sync-xhr=(self), usb=(self), xr-spatial-tracking=(self)"
# 	}

# 	header /console* {
# 		-Content-Security-Policy
# 	}

# 	route /v1* {
# 		# API (Hasura)
# 		reverse_proxy localhost:$HASURA_PORT {
# 			header_up -X-Hasura-Role
# 		}
# 	}

# 	route /v2* {
# 		# API (Hasura)
# 		reverse_proxy localhost:$HASURA_PORT {
# 			header_up -X-Hasura-Role
# 		}
# 	}

# 	route /console* {
# 		# Admin panel (Hasura)
# 		reverse_proxy localhost:$HASURA_PORT {
# 			header_up -X-Hasura-Role
# 		}
# 	}

# 	route /healthz {
# 		# Health check (Hasura)
# 		reverse_proxy localhost:$HASURA_PORT {
# 			header_up -X-Hasura-Role
# 		}
# 	}

# 	route /auth* {
# 		# Authentication server (Express.js)
# 		reverse_proxy localhost:$AUTH_PORT {
# 			header_up -X-Hasura-Role
# 		}
# 	}

# 	route /* {
# 		# Static files (Client)
# 		reverse_proxy localhost:$CLIENT_PORT {
# 			header_up -X-Hasura-Role
# 		}
# 	}
# }
