services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:10.11.6@sha256:7b29a93a6020f8d5f6c60df381a5ab7d57aa83cda4beb3631bd2bfbbcb1497af
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ={{{global:TIMEZONE}}}
      - JELLYFIN_PublishedServerUrl=https://{{{domainForApp "jellyfin"}}}
    volumes:
      - /docker/jellyfin:/config
      # mount baremetal paths since data was migrated from a baremetal insall
      - /docker/jellyfin/data:/var/lib/jellyfin
      - /docker/jellyfin:/etc/jellyfin
      - /mnt/media:/mnt/media
    ports:
      #   - 8096:8096 # http
      #   - 8920:8920 # https
      - 7359:7359/udp # optional - auto-discovery
      - 1900:1900/udp # optional - service discovery
    devices:
      # select VAAPI acceleration in Dashboard > Playback > Transcoding
      # device: /dev/dri/renderD128
      # use 'radeontop' to measure gpu usage
      - /dev/dri:/dev/dri # renderD128, card0/1
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`{{{domainForApp "jellyfin"}}}`)
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=porkbun
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    networks:
      - traefik

networks:
  traefik:
    external: true
