services:
  navidrome:
    image: deluan/navidrome:0.58.0@sha256:2ae037d464de9f802d047165a13b1c9dc2bdbb14920a317ae4aef1233adc0a3c
    container_name: navidrome
    user: 0:0
    # ports:
    #   - "4533:4533"
    restart: unless-stopped
    environment:
      ND_LASTFM_APIKEY: "{{{SECRET_LASTFM_APIKEY}}}"
      ND_LASTFM_SECRET: "{{{SECRET_LASTFM_SECRET}}}"
      # https://www.navidrome.org/docs/usage/configuration-options/#environment-variables
      ND_DEFAULTTHEME: "Spotify-ish"
      ND_DEFAULTUIVOLUME: 50
    volumes:
      - /docker/navidrome:/data
      - /mnt/media/music:/music:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.navidrome.rule=Host(`{{{domainForApp "navidrome"}}}`)
      - traefik.http.routers.navidrome.entrypoints=https
      - traefik.http.routers.navidrome.tls=true
      - traefik.http.routers.navidrome.tls.certresolver=porkbun
      - traefik.http.routers.navidrome.service=navidrome
      - traefik.http.services.navidrome.loadbalancer.server.port=4533
    networks:
      - traefik

networks:
  traefik:
    external: true
