id = 201
hostname = "servarr-pulumi"
enabled = false

description = "servarr media stack"
tags = ["media", "automation"]
services = ["traefik"] # TODO enable servarr

[cpu]
cores = 2

[memory]
dedicated = 8192
swap = 4096

[disk]
size = 64

[[mountPoints]]
volume = "/void/media"
mountPoint = "/mnt/media"

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
