# verified
id = 201
hostname = "servarr-pulumi"
enabled = false

description = "servarr media stack"

[stacks]
traefik = {}
dozzle = {}
komodo = {}
servarr = {}

[cpu]
cores = 2

[memory]
dedicated = 8192
swap = 4096

[disk]
size = 64

[[firewallRules]]
enabled = true
type = "in"
action = "ACCEPT"
proto = "tcp"
comment = "qbittorrent bittorrent"
dport = "6881"

[[mountPoints]]
volume = "/void/media"
mountPoint = "/mnt/media"

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"

[[provisioners]]
type = "script"
name = "install-periphery"
script = "provisioners/scripts/install-periphery.sh"

[[provisioners]]
type = "ansible"
name = "configure-vpn"
playbook = "provisioners/ansible/configure-tun-access.yaml"
replayable = false

[provisioners.variables]
lxc_id = 201

[provisioners.connection]
host = "{{{homelab-pve:homelabDomain}}}"
