services:
  ac:
    image: copyparty/ac:1.20.5@sha256:4b38c63a106960bcdc73becbe7545b152ba9cbc22a7d30fb2564498309ca83d3
    container_name: copyparty
    restart: unless-stopped
    user: "0:0"
    # ports:
    #   - '3939:3939'
    volumes:
      - /docker/copyparty:/cfg
      - ./copyparty.conf:/cfg/copyparty.conf
      - /mnt:/mnt
    labels:
      - traefik.enable=true
      - traefik.http.routers.copyparty.rule=Host(`{{{domainForApp "copyparty"}}}`)
      - traefik.http.routers.copyparty.entrypoints=https
      - traefik.http.routers.copyparty.tls=true
      - traefik.http.routers.copyparty.tls.certresolver=porkbun
      - traefik.http.routers.copyparty.service=copyparty
      - traefik.http.services.copyparty.loadbalancer.server.port=3939
      - traefik.http.routers.copyparty.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
