services:
  ac:
    image: copyparty/ac:1.19.21@sha256:e6ff5501752dc714473dcfe2da4eddb8d1fbf38b74573e59a0c812758272a9e5
    container_name: copyparty
    restart: unless-stopped
    user: "0:0"
    # ports:
    #   - '3939:3939'
    volumes:
      - /docker/copyparty:/cfg
      - ./copyparty.conf:/cfg/copyparty.conf
      - /mnt:/mnt
    labels:
      - traefik.enable=true
      - traefik.http.routers.copyparty.rule=Host(`{{{domainForApp "copyparty"}}}`)
      - traefik.http.routers.copyparty.entrypoints=https
      - traefik.http.routers.copyparty.tls=true
      - traefik.http.routers.copyparty.tls.certresolver=porkbun
      - traefik.http.routers.copyparty.service=copyparty
      - traefik.http.services.copyparty.loadbalancer.server.port=3939
    networks:
      - traefik

networks:
  traefik:
    external: true
