services:
  ac:
    image: copyparty/ac:1.20.6@sha256:1d8684f0801137355d928c369cec93c28d6127dcc7851a84ade7e6782ea9a1cd
    container_name: copyparty
    restart: unless-stopped
    user: "0:0"
    # ports:
    #   - '3939:3939'
    volumes:
      - /docker/copyparty:/cfg
      - ./copyparty.conf:/cfg/copyparty.conf
      - /mnt:/mnt
    labels:
      - traefik.enable=true
      - traefik.http.routers.copyparty.rule=Host(`{{{domainForApp "copyparty"}}}`)
      - traefik.http.routers.copyparty.entrypoints=https
      - traefik.http.routers.copyparty.tls=true
      - traefik.http.routers.copyparty.tls.certresolver=porkbun
      - traefik.http.routers.copyparty.service=copyparty
      - traefik.http.services.copyparty.loadbalancer.server.port=3939
      - traefik.http.routers.copyparty.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
