---
- Developer:
    - HaC Github:
        - abbr: HaC
          href: https://github.com/minchingtonak/HaC

- Social:
    - r/selfhosted:
        - icon: reddit.png
          href: https://reddit.com/r/selfhosted
