// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Host extends pulumi.CustomResource {
    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: HostState, opts?: pulumi.CustomResourceOptions): Host {
        return new Host(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ansible:index/host:Host';

    /**
     * Returns true if the given object is an instance of Host.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Host {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Host.__pulumiType;
    }

    /**
     * List of group names.
     */
    declare public readonly groups: pulumi.Output<string[] | undefined>;
    declare public readonly hostId: pulumi.Output<string>;
    /**
     * Name of the host.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Map of variables.
     */
    declare public readonly variables: pulumi.Output<{[key: string]: string} | undefined>;

    /**
     * Create a Host resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: HostArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: HostArgs | HostState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as HostState | undefined;
            resourceInputs["groups"] = state?.groups;
            resourceInputs["hostId"] = state?.hostId;
            resourceInputs["name"] = state?.name;
            resourceInputs["variables"] = state?.variables;
        } else {
            const args = argsOrState as HostArgs | undefined;
            resourceInputs["groups"] = args?.groups;
            resourceInputs["hostId"] = args?.hostId;
            resourceInputs["name"] = args?.name;
            resourceInputs["variables"] = args?.variables;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Host.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Host resources.
 */
export interface HostState {
    /**
     * List of group names.
     */
    groups?: pulumi.Input<pulumi.Input<string>[]>;
    hostId?: pulumi.Input<string>;
    /**
     * Name of the host.
     */
    name?: pulumi.Input<string>;
    /**
     * Map of variables.
     */
    variables?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a Host resource.
 */
export interface HostArgs {
    /**
     * List of group names.
     */
    groups?: pulumi.Input<pulumi.Input<string>[]>;
    hostId?: pulumi.Input<string>;
    /**
     * Name of the host.
     */
    name?: pulumi.Input<string>;
    /**
     * Map of variables.
     */
    variables?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
