---
- name: Configure LXC container for TUN/TAP access
  hosts: all
  become: true

  tasks:
    - name: Check if LXC container exists
      ansible.builtin.stat:
        path: '/etc/pve/lxc/{{ lxc_id }}.conf'
      register: lxc_config_file

    - name: Fail if LXC container doesn't exist
      ansible.builtin.fail:
        msg: 'LXC container {{ lxc_id }} configuration file not found'
      when: not lxc_config_file.stat.exists

    - name: Add TUN/TAP device configuration to LXC container
      ansible.builtin.blockinfile:
        path: '/etc/pve/lxc/{{ lxc_id }}.conf'
        block: |
          lxc.cgroup2.devices.allow: c 10:200 rwm
          lxc.mount.entry: /dev/net dev/net none bind,create=dir
          lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
        marker: '# {mark} ANSIBLE MANAGED - TUN/TAP CONFIGURATION'
        backup: true
      notify: Restart container

    - name: Wait for container to reboot
      ansible.builtin.pause:
        seconds: 20

  handlers:
    - name: Restart container
      ansible.builtin.command: 'pct reboot {{ lxc_id }}'
      changed_when: true
