---
- name: Setup Gitea
  hosts: all
  become: true
  vars:
    gitea_container_name: gitea
    git_user_uid: 1000
    git_user_gid: 1000
    void_access_gid: 10000

  tasks:
    - name: Create void-access group
      ansible.builtin.group:
        name: void-access
        gid: '{{ void_access_gid }}'
        state: present

    - name: Create git group
      ansible.builtin.group:
        name: git
        gid: '{{ git_user_gid }}'
        state: present

    - name: Create git user
      ansible.builtin.user:
        name: git
        uid: '{{ git_user_uid }}'
        group: git
        groups: void-access
        shell: /bin/bash
        home: /home/git
        create_home: true
        state: present

    - name: Create docker-shell script
      ansible.builtin.copy:
        dest: /home/git/docker-shell
        content: |
          #!/bin/sh
          /usr/bin/docker exec -i -u git --env SSH_ORIGINAL_COMMAND="$SSH_ORIGINAL_COMMAND" {{ gitea_container_name }} sh "$@"
        mode: '0755'
        owner: git
        group: git

    - name: Set git user shell to docker-shell
      ansible.builtin.user:
        name: git
        shell: /home/git/docker-shell

    - name: Add Match User git block to sshd_config
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Match User git
            AuthorizedKeysCommandUser git
            AuthorizedKeysCommand /usr/bin/docker exec -i -u git {{ gitea_container_name }} /usr/local/bin/gitea keys -e git -u %u -t %t -k %k
        marker: '# {mark} ANSIBLE MANAGED BLOCK - Gitea SSH'
        insertafter: EOF

    - name: Reboot with systemctl
      ansible.builtin.systemd:
        name: reboot.target
        state: started
      async: 1
      poll: 0
      failed_when: false

    - name: Wait for system to come back
      ansible.builtin.wait_for_connection:
        delay: 20
        timeout: 600
