services:
  picard:
    image: ghcr.io/minchingtonak/picard:2.13.3@sha256:c98fd975f631a3d89230e6b381a54995a98d75e03f78988d8ab2726e2265ceaf
    container_name: musicbrainz-picard
    restart: always
    # ports:
    #   - "5800:5800"
    #   - "5900:5900"
    environment:
      USER_ID: 0
      GROUP_ID: 0
      TZ: "{{{global:TIMEZONE}}}"
    volumes:
      - "/docker/picard:/config:rw"
      - "/mnt/media/music:/music:rw"
      - "/mnt/media/downloads:/downloads:rw"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.picard.rule=Host(`{{{domainForApp "picard"}}}`)
      - traefik.http.routers.picard.entrypoints=https
      - traefik.http.routers.picard.tls=true
      - traefik.http.routers.picard.tls.certresolver=porkbun
      - traefik.http.routers.picard.service=picard
      - traefik.http.services.picard.loadbalancer.server.port=5800
      - traefik.http.routers.picard.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
