# verified
id = 200
hostname = "copyparty"

description = "copyparty lightweight fileserver container"

[stacks]
traefik = {}
dozzle = {}
copyparty = {}

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 512

[disk]
size = 4

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/copyparty"
mount_point = "/docker"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/audiobooks"
mount_point = "/mnt/audiobooks"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/backups"
mount_point = "/mnt/backups"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/documents"
mount_point = "/mnt/documents"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/drive"
mount_point = "/mnt/drive"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/media"
mount_point = "/mnt/media"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/photos"
mount_point = "/mnt/photos"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/podcasts"
mount_point = "/mnt/podcasts"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/restic"
mount_point = "/mnt/restic"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
