# verified
id = 200
hostname = "copyparty"

description = "copyparty lightweight fileserver container"

[stacks]
traefik = {}
dozzle = {}
copyparty = {}

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 512

[disk]
size = 4

[[mountPoints]]
volume = "{{{@pve.lxc.appDataDirectory}}}/copyparty"
mountPoint = "/docker"

[[mountPoints]]
volume = "{{{@pve.storage.mass.path}}}/audiobooks"
mountPoint = "/mnt/audiobooks"

[[mountPoints]]
volume = "{{{@pve.storage.mass.path}}}/backups"
mountPoint = "/mnt/backups"

[[mountPoints]]
volume = "{{{@pve.storage.mass.path}}}/documents"
mountPoint = "/mnt/documents"

[[mountPoints]]
volume = "{{{@pve.storage.mass.path}}}/drive"
mountPoint = "/mnt/drive"

[[mountPoints]]
volume = "{{{@pve.storage.mass.path}}}/media"
mountPoint = "/mnt/media"

[[mountPoints]]
volume = "{{{@pve.storage.mass.path}}}/photos"
mountPoint = "/mnt/photos"

[[mountPoints]]
volume = "{{{@pve.storage.mass.path}}}/podcasts"
mountPoint = "/mnt/podcasts"

[[mountPoints]]
volume = "{{{@pve.storage.mass.path}}}/restic"
mountPoint = "/mnt/restic"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
