# verified
id = 206
hostname = "gitea"

description = "lightweight private git server and github mirror"

[stacks]
traefik = {}
dozzle = {}
gitea = {}

[cpu]
cores = 1

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 16

[[firewallRules]]
enabled = true
type = "in"
action = "ACCEPT"
dport = "222"
proto = "tcp"
comment = "gitea ssh"

[[mountPoints]]
volume = "{{{@pve.lxc.appdata}}}/gitea"
mountPoint = "/docker"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/gitea-setup.yaml"
replayable = true

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
