# verified
id = 204
hostname = "jellyseerr-pulumi"

description = "easy to use media recommendation and request app"

[stacks]
traefik = {}
jellyseerr = {}

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 8

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
