# verified
id = 204
hostname = "jellyseerr"

description = "easy to use media recommendation and request app"

[stacks]
traefik = {}
dozzle = {}
jellyseerr = {}
movie-roulette = {}
watcharr = {}

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 8

[[mountPoints]]
volume = "{{{@pve.lxc.appDataDirectory}}}/jellyseerr"
mountPoint = "/docker"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
