# verified
hostname = "jellyseerr"

description = "easy to use media recommendation and request app"

[stacks]
traefik = {}
dozzle = {}
jellyseerr = {}
movie-roulette = {}
watcharr = {}

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 8

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/jellyseerr"
mount_point = "/docker"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
