# verified
hostname = "jellyfin"

description = "jellyfin media player server"

[stacks]
traefik = {}
dozzle = {}
jellyfin = {}

[cpu]
cores = 4

[memory]
dedicated = 4096
swap = 2048

[disk]
size = 16

[[firewall_rules]]
enabled = true
type = "in"
action = "ACCEPT"
dport = "1900"
proto = "udp"
comment = "jellyfin service discovery"

[[firewall_rules]]
enabled = true
type = "in"
action = "ACCEPT"
dport = "7359"
proto = "udp"
comment = "jellyfin auto discovery"

[[device_passthroughs]]
path = "/dev/dri/card1"
uid = 0
gid = 44
mode = "0660"

[[device_passthroughs]]
path = "/dev/dri/renderD128"
uid = 0
gid = 104
mode = "0660"

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/jellyfin"
mount_point = "/docker"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/media"
mount_point = "/mnt/media"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
