hostname = "syncthing"
description = "simple file syncing across devices"
start_on_boot = false

[stacks]
traefik = {}
dozzle = {}
syncthing = {}

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 8

[[firewall_rules]]
enabled = true
type = "in"
action = "ACCEPT"
dport = "22000"
proto = "tcp"
comment = "syncthing-sync"

[[firewall_rules]]
enabled = true
type = "in"
action = "ACCEPT"
dport = "22000"
proto = "udp"
comment = "syncthing-sync-quic"

[[firewall_rules]]
enabled = true
type = "in"
action = "ACCEPT"
dport = "21027"
proto = "udp"
comment = "syncthing-local-discovery"

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/syncthing"
mount_point = "/docker"

[[mount_points]]
volume = "/void/documents"
mount_point = "/mnt/documents"

[[mount_points]]
volume = "/void/drive"
mount_point = "/mnt/drive"

[[mount_points]]
volume = "/void/media"
mount_point = "/mnt/media"

[[mount_points]]
volume = "/void/photos"
mount_point = "/mnt/photos"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
