id = 212
hostname = "syncthing-pulumi"

description = "simple file syncing across devices"

[stacks]
traefik = {}
syncthing = {}

[cpu]
cores = 2

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 8

[[mountPoints]]
volume = "/void/documents"
mountPoint = "/mnt/documents"

[[mountPoints]]
volume = "/void/drive"
mountPoint = "/mnt/drive"

[[mountPoints]]
volume = "/void/media"
mountPoint = "/mnt/media"

[[mountPoints]]
volume = "/void/photos"
mountPoint = "/mnt/photos"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
