id = 217
hostname = "archiver-pulumi"
enabled = true

description = "worker for archive team warrior"
services = ["traefik", "archiveteam-warrior"]

[cpu]
cores = 2

[memory]
dedicated = 4096
swap = 2048

[disk]
size = 8

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
