# verified
id = 207
hostname = "immich-pulumi"

description = "private image server"

[stacks]
traefik = {}
immich = {}

[cpu]
cores = 2

[memory]
dedicated = 4096
swap = 2048

[disk]
size = 64

[[mountPoints]]
volume = "/void/photos"
mountPoint = "/mnt/photos"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
