# verified
id = 203
hostname = "jellyfin"

description = "jellyfin media player server"

[stacks]
traefik = {}
dozzle = {}
jellyfin = {}

[cpu]
cores = 4

[memory]
dedicated = 4096
swap = 2048

[disk]
size = 16

[[firewallRules]]
enabled = true
type = "in"
action = "ACCEPT"
dport = "1900"
proto = "udp"
comment = "jellyfin service discovery"

[[firewallRules]]
enabled = true
type = "in"
action = "ACCEPT"
dport = "7369"
proto = "udp"
comment = "jellyfin auto discovery"

[[devicePassthroughs]]
path = "/dev/dri/card1"
uid = 0
gid = 44
mode = "0660"

[[devicePassthroughs]]
path = "/dev/dri/renderD128"
uid = 0
gid = 104
mode = "0660"

[[mountPoints]]
volume = "{{{@pve.lxc.appdata}}}/jellyfin"
mountPoint = "/docker"

[[mountPoints]]
volume = "{{{@pve.storage.pools.mass}}}/media"
mountPoint = "/mnt/media"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
