id = 216
hostname = "music-pulumi"

description = "assorted audio management apps"

[stacks]
traefik = {}
audiobookshelf = {}
navidrome = {}
slskd = {}
your-spotify = {}

[cpu]
cores = 2

[memory]
dedicated = 8192
swap = 4096

[disk]
size = 16

[[mountPoints]]
volume = "/void/audiobooks"
mountPoint = "/mnt/audiobooks"

[[mountPoints]]
volume = "/void/media"
mountPoint = "/mnt/media"

[[mountPoints]]
volume = "/void/podcasts"
mountPoint = "/mnt/podcasts"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
