# PVE Host Configuration Reference
# This file shows all available configuration options for PVE hosts

[pve]
endpoint = "https://pve.local:8006"  # PVE API endpoint URL
node = "pve-node"                    # PVE node name

[pve.auth]
username = "root@pam"                # PVE username
password = "password"                # PVE password
insecure = false                     # Skip TLS verification (default: false)

[storage]
templates = "local"                  # Datastore for container templates
containers = "local-lvm"             # Default datastore for containers (optional)
backups = "backup-storage"           # Datastore for backups (optional)

[dns]
domain = "example.com"               # PVE domain
servers = ["8.8.8.8", "1.1.1.1"]    # DNS servers (optional)

[lxc.hosts]
# Define which LXC hosts to create
# Each host corresponds to a .hbs.toml file in the lxc-hosts/ directory
example-host = { enabled = true }    # Enable/disable specific hosts
another-host = { enabled = false }   # Disabled host example

[lxc.network]
domain = "local.dev"                 # Base domain for containers
subnet = "192.168.1"                 # IP subnet prefix (without trailing dot)
gateway = "192.168.1.1"              # Network gateway

[lxc.auth]
password = "container-root-password" # Default root password for containers

[lxc.ssh]
publicKey = "ssh-ed25519 AAAAC3..."  # SSH public key for container access
privateKey = """-----BEGIN OPENSSH PRIVATE KEY-----
...
-----END OPENSSH PRIVATE KEY-----""" # SSH private key for container access

[lxc.dns.porkbun]
apiKey = "pk1_..."                   # Porkbun API key for DNS management
secretKey = "sk1_..."                # Porkbun secret key for DNS management