services:
  memos:
    image: neosmemo/memos:0.25.3@sha256:40db300a188ede0c2cf1fc0c49741a03077478d6891fd3ace05c16d702b536a6
    container_name: memos
    # ports:
    #   - "5230:5230"
    volumes:
      - /docker/memos:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_PORT=5230
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.memos.rule=Host(`{{{domainForApp "memos"}}}`)
      - traefik.http.routers.memos.entrypoints=https
      - traefik.http.routers.memos.tls=true
      - traefik.http.routers.memos.tls.certresolver=porkbun
      - traefik.http.routers.memos.service=memos
      - traefik.http.services.memos.loadbalancer.server.port=5230
    networks:
      - traefik

networks:
  traefik:
    external: true
