services:
  server:
    image: codeberg.org/forgejo/forgejo:15.0.1@sha256:bff07e43f5c84449e9dc6dca2c0a16c6f9eb285405d7f1bc631a360fd963f3fc
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /docker/forgejo:/data
      # NOTE: for first-time setup, comment the below line out, otherwise forgejo will not go into setup mode
      - ./conf/app.ini:/data/gitea/conf/app.ini:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #   - "3000:3000"
      - "222:22"
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgejo.rule=Host(`{{{domainForApp "forgejo"}}}`)
      - traefik.http.routers.forgejo.entrypoints=https
      - traefik.http.routers.forgejo.tls=true
      - traefik.http.routers.forgejo.tls.certresolver=porkbun
      - traefik.http.routers.forgejo.service=forgejo
      - traefik.http.services.forgejo.loadbalancer.server.port=3000
    networks:
      - traefik

networks:
  traefik:
    external: true
