services:
  server:
    image: codeberg.org/forgejo/forgejo:13.0.3@sha256:88858e7f592f82d4f650713c7bed8c0cd792d7f71475a7467c5650a31cd2eda9
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /docker/forgejo:/data
      # NOTE: for first-time setup, comment the below line out, otherwise forgejo will not go into setup mode
      - ./conf/app.ini:/data/gitea/conf/app.ini:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "3000:3000"
    #   - "222:22"
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgejo.rule=Host(`{{{domainForApp "forgejo"}}}`)
      - traefik.http.routers.forgejo.entrypoints=https
      - traefik.http.routers.forgejo.tls=true
      - traefik.http.routers.forgejo.tls.certresolver=porkbun
      - traefik.http.routers.forgejo.service=forgejo
      - traefik.http.services.forgejo.loadbalancer.server.port=3000
      #
      - traefik.tcp.routers.forgejo-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.forgejo-ssh.entrypoints=ssh-222-tcp
      - traefik.tcp.routers.forgejo-ssh.service=forgejo-ssh
      - traefik.tcp.services.forgejo-ssh.loadbalancer.server.port=22
    networks:
      - traefik

networks:
  traefik:
    external: true
