services:
  tailscale:
    image: tailscale/tailscale:v1.88.4@sha256:360e10ad95ad03950f66df03e0dab66287f9f89076ee4012d50bc6adceafcdf3
    container_name: tailscale
    hostname: tailscale
    user: "0:10000"
    environment:
      - TS_AUTHKEY={{{SECRET_TAILSCALE_AUTHKEY}}}
      - TS_EXTRA_ARGS=--ssh --advertise-routes={{{TAILSCALE_SUBNET_ROUTES}}}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - /docker/tailscale:/var/lib/tailscale # tailscale folder must be owned by lxc-root, permission errors otherwise
    cap_add:
      - net_admin
    network_mode: host
    restart: unless-stopped
