services:
  tailscale:
    image: tailscale/tailscale:v1.90.9@sha256:9975353aae933e8fbd1a81226d092a9225b9a0f98b173d365a9d525eca1cc298
    container_name: tailscale
    hostname: tailscale
    user: "0:10000"
    environment:
      - TS_AUTHKEY={{{SECRET_TAILSCALE_AUTHKEY}}}
      - TS_EXTRA_ARGS=--ssh --advertise-routes={{{TAILSCALE_SUBNET_ROUTES}}}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - /docker/tailscale:/var/lib/tailscale # tailscale folder must be owned by lxc-root, permission errors otherwise
    cap_add:
      - net_admin
    network_mode: host
    restart: unless-stopped
