services:
  tailscale:
    image: tailscale/tailscale:v1.90.8@sha256:4dacf554cf34e84c15fb816aa68fb3428993c3d27feeafb86a9b3eb94248c40f
    container_name: tailscale
    hostname: tailscale
    user: "0:10000"
    environment:
      - TS_AUTHKEY={{{SECRET_TAILSCALE_AUTHKEY}}}
      - TS_EXTRA_ARGS=--ssh --advertise-routes={{{TAILSCALE_SUBNET_ROUTES}}}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - /docker/tailscale:/var/lib/tailscale # tailscale folder must be owned by lxc-root, permission errors otherwise
    cap_add:
      - net_admin
    network_mode: host
    restart: unless-stopped
