services:
  apprise:
    image: caronc/apprise:1.2.1@sha256:127b3834f0679502529397ead8ffeaadf5189019c4c863fa6652e9b942fdccf8
    environment:
      - APPRISE_WORKER_COUNT=1
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_DEFAULT_THEME=dark
      - APPRISE_DEFAULT_CONFIG_ID=homelab
      - APPRISE_CONFIG_LOCK=yes # should not be able to edit through UI
      - PGID=0
      - PUID=0
    volumes:
      - /docker/apprise/attach:/attach
      - /docker/apprise/plugin:/plugin
      - ./config:/config
    restart: unless-stopped
    # ports:
    #   - 8000:8000
    container_name: apprise
    labels:
      - traefik.enable=true
      - traefik.http.routers.apprise.rule=Host(`{{{domainForApp "apprise"}}}`)
      - traefik.http.routers.apprise.entrypoints=https
      - traefik.http.routers.apprise.tls=true
      - traefik.http.routers.apprise.tls.certresolver=porkbun
      - traefik.http.routers.apprise.service=apprise
      - traefik.http.services.apprise.loadbalancer.server.port=8000
    networks:
      - traefik

networks:
  traefik:
    external: true
