# HEY, YOU! READ THE DOCS BEFORE YOU DO ANYTHING!
# https://spotizerr-phoenix.readthedocs.io
name: spotizerr-phoenix
services:
  spotizerr:
    image: spotizerrphoenix/spotizerr:4.0.15@sha256:545aa36e7c515a6a6a3d716bb33e950b6c991e01ef08db80c40e5b33580a1315
    user: "0:0"
    volumes:
      # Ensure these directories and the .cache file exist and are writable by the container user
      - /docker/spotizerr/.cache:/app/.cache # cache file
      - /docker/spotizerr/data:/app/data # data directory, contains config, creds, watch, history
      - /docker/spotizerr/logs:/app/logs # logs directory, contains logs
      - /mnt/media/downloads/spotizerr:/app/downloads # downloads directory, contains downloaded files
    # ports:
    # - 7171:7171
    container_name: spotizerr-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.spotizerr.rule=Host(`{{{domainForApp "spotizerr"}}}`)
      - traefik.http.routers.spotizerr.entrypoints=https
      - traefik.http.routers.spotizerr.tls=true
      - traefik.http.routers.spotizerr.tls.certresolver=porkbun
      - traefik.http.routers.spotizerr.service=spotizerr
      - traefik.http.services.spotizerr.loadbalancer.server.port=7171
      - traefik.http.routers.spotizerr.middlewares=oidc-auth@file
    networks:
      - traefik

  redis:
    image: redis:alpine@sha256:6cbef353e480a8a6e7f10ec545f13d7d3fa85a212cdcc5ffaf5a1c818b9d3798
    container_name: spotizerr-redis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /docker/spotizerr/redis:/data
    command: sh -c 'redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes'

networks:
  traefik:
    external: true
