node = "t480"
endpoint = "https://192.168.0.90:8006"
ip = "192.168.0.90"

[auth]
username = "{{{SECRET_USERNAME}}}"
password = "{{{SECRET_PASSWORD}}}"
insecure = true

[ssh]
user = "{{{SECRET_SSH_USER}}}"
public_key = "{{{SECRET_CONTAINER_SSH_PUBLIC_KEY}}}"
private_key = """{{{SECRET_CONTAINER_SSH_PRIVATE_KEY}}}"""

[storage]
fast = { name = "fast", path = "/fast" }

[[files]]
datastore_id = "local"
content_type = "vztmpl"
url = "http://download.proxmox.com/images/system/debian-12-standard_12.7-1_amd64.tar.zst"
checksum = "39f6d06e082d6a418438483da4f76092ebd0370a91bad30b82ab6d0f442234d63fe27a15569895e34d6d1e5ca50319f62637f7fb96b98dbde4f6103cf05bff6d"
checksum_algorithm = "sha512"
overwrite_unmanaged = true
retain_on_delete = true

[lxc]
app_data_dir = "/fast/appdata"

[lxc.hosts]
# backup = { id = 202 }
[lxc.hosts.backup]
id = 202
[[lxc.hosts.backup.mount_points]]
volume = "/void/backups"
mount_point = "/mnt/backup-data/backups"

gitea = { id = 206 }
immich = { id = 207 }
tools = { id = 208 }
windmill = { id = 209 }
tailscale = { id = 211 }
admin = { id = 213 }
paperless = { id = 214 }
life = { id = 215 }

[lxc.network]
domain = "akmin.dev"
subnet = "192.168.0"
gateway = "192.168.0.1"

[lxc.auth]
password = "{{{SECRET_CONTAINER_ROOT_PASSWORD}}}"

[lxc.ssh]
user = "{{{SECRET_CONTAINER_SSH_USER}}}"
public_key = "{{{SECRET_CONTAINER_SSH_PUBLIC_KEY}}}"
private_key = """{{{SECRET_CONTAINER_SSH_PRIVATE_KEY}}}"""

[providers.dns.porkbun]
api_key = "{{{SECRET_PORKBUN_API_KEY}}}"
secret_key = "{{{SECRET_PORKBUN_SECRET_KEY}}}"
