services:
  backrest:
    image: garethgeorge/backrest:v1.9.2@sha256:f8306faef0a3cbedc7daa55756f1d4c105d8c104aa773656bdad4fa8553dab5a
    container_name: backrest
    hostname: backrest
    user: "0:10000"
    volumes:
      - /docker/backrest/data:/data
      - /docker/backrest/config:/config
      - /docker/backrest/cache:/cache
      - /docker/backrest/tmp:/tmp
      - /mnt/backup-data:/userdata # Mount local paths to backup
      - /mnt/repos:/repos # Mount local repos (optional for remote storage)
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ={{{global:TIMEZONE}}}
    # ports:
    #   - "9898:9898"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.backrest.rule=Host(`{{{domainForApp "backrest"}}}`)
      - traefik.http.routers.backrest.entrypoints=https
      - traefik.http.routers.backrest.tls=true
      - traefik.http.routers.backrest.tls.certresolver=porkbun
      - traefik.http.routers.backrest.service=backrest
      - traefik.http.services.backrest.loadbalancer.server.port=9898
    networks:
      - traefik

networks:
  traefik:
    external: true
