services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:2.9.2@sha256:3fcfa4d6b6ff22fdbf96ff2aae98dc2fb6d8c1ba0afab1dd2fdfdcdc9ab543c4
    # ports:
    #   - '8080:8080'
    volumes:
      - /docker/stirling-pdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /docker/stirling-pdf/extraConfigs:/configs
      - /docker/stirling-pdf/customFiles:/customFiles/
      - /docker/stirling-pdf/logs:/logs/
      - /docker/stirling-pdf/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_US
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.stirlingpdf.rule=Host(`{{{domainForApp "stirling-pdf"}}}`)
      - traefik.http.routers.stirlingpdf.entrypoints=https
      - traefik.http.routers.stirlingpdf.tls=true
      - traefik.http.routers.stirlingpdf.tls.certresolver=porkbun
      - traefik.http.routers.stirlingpdf.service=stirlingpdf
      - traefik.http.services.stirlingpdf.loadbalancer.server.port=8080
      - traefik.http.routers.stirlingpdf.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
