services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest@sha256:bfe2b8dd378c4f3d5fc1d2fc7649a357d0916b3a713022aa70ac3f08d6302cbc
    # ports:
    #   - '8080:8080'
    volumes:
      - /docker/stirling-pdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /docker/stirling-pdf/extraConfigs:/configs
      - /docker/stirling-pdf/customFiles:/customFiles/
      - /docker/stirling-pdf/logs:/logs/
      - /docker/stirling-pdf/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_US
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.stirlingpdf.rule=Host(`{{{domainForApp "stirling-pdf"}}}`)
      - traefik.http.routers.stirlingpdf.entrypoints=https
      - traefik.http.routers.stirlingpdf.tls=true
      - traefik.http.routers.stirlingpdf.tls.certresolver=porkbun
      - traefik.http.routers.stirlingpdf.service=stirlingpdf
      - traefik.http.services.stirlingpdf.loadbalancer.server.port=8080
    networks:
      - traefik

networks:
  traefik:
    external: true
