services:
  sonobarr:
    image: ghcr.io/dodelidoo-labs/sonobarr:0.12.1@sha256:c1581d2a3e065478f357adf4a6e5384091b537d3347a0a21c4bb999347f27575
    container_name: sonobarr
    env_file:
      - .env
    volumes:
      - /docker/sonobarr:/sonobarr/config
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "5000:5000"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonobarr.rule=Host(`{{{domainForApp "sonobarr"}}}`)
      - traefik.http.routers.sonobarr.entrypoints=https
      - traefik.http.routers.sonobarr.tls=true
      - traefik.http.routers.sonobarr.tls.certresolver=porkbun
      - traefik.http.routers.sonobarr.service=sonobarr
      - traefik.http.services.sonobarr.loadbalancer.server.port=5000
    networks:
      - traefik

networks:
  traefik:
    external: true
