services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.6.2@sha256:1cc51e5b36fa7ec31368d3efb24ba362be6dce20f3cc0a2852843527bd5110f0
    restart: unless-stopped
    env_file: .env
    # ports:
    #   - 1411:1411
    volumes:
      - "/docker/pocket-id:/app/data"
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.pocket-id.rule=Host(`{{{domainForApp "pocket-id"}}}`)
      - traefik.http.routers.pocket-id.entrypoints=https
      - traefik.http.routers.pocket-id.tls=true
      - traefik.http.routers.pocket-id.tls.certresolver=porkbun
      - traefik.http.routers.pocket-id.service=pocket-id
      - traefik.http.services.pocket-id.loadbalancer.server.port=1411
    networks:
      - traefik

networks:
  traefik:
    external: true
