services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.12.0@sha256:8d962f611390a1cca667eed32a29e9467e9c01c523e2db3ad00f667372067f9d
    container_name: mealie
    restart: always
    # ports:
    #   - "9926:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /docker/mealie:/app/data
    environment:
      PUID: 0
      PGID: 0
      ALLOW_SIGNUP: "false"
      TZ: "{{{global:TIMEZONE}}}"
      BASE_URL: '{{{domainForApp "mealie"}}}'
    labels:
      - traefik.enable=true
      - traefik.http.routers.mealie.rule=Host(`{{{domainForApp "mealie"}}}`)
      - traefik.http.routers.mealie.entrypoints=https
      - traefik.http.routers.mealie.tls=true
      - traefik.http.routers.mealie.tls.certresolver=porkbun
      - traefik.http.routers.mealie.service=mealie
      - traefik.http.services.mealie.loadbalancer.server.port=9000
    networks:
      - traefik

networks:
  traefik:
    external: true
