# verified
id = 203
hostname = "jellyfin-pulumi"
enabled = false

description = "jellyfin media player server"
stacks = ["traefik", "jellyfin"]

[cpu]
cores = 4

[memory]
dedicated = 4096
swap = 2048

[disk]
size = 16

[[firewallRules]]
type = "in"
action = "ACCEPT"
dport = "1900"
proto = "udp"
comment = "jellyfin service discovery"

[[firewallRules]]
type = "in"
action = "ACCEPT"
dport = "7369"
proto = "udp"
comment = "jellyfin auto discovery"

[[devicePassthroughs]]
path = "/dev/dri/card0"
uid = 0
gid = 44
mode = "0660"

[[devicePassthroughs]]
path = "/dev/dri/renderD128"
uid = 0
gid = 104
mode = "0660"

[[mountPoints]]
volume = "/void/media"
mountPoint = "/mnt/media"

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
