services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    # ports:
    #   - 13378:80
    volumes:
      - /mnt/audiobooks:/audiobooks
      - /mnt/podcasts:/podcasts
      - /docker/audiobookshelf/config:/config
      - /docker/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.{{{PARENT:CONTAINER_DOMAIN}}}`)
      - traefik.http.routers.audiobookshelf.entrypoints=https
      - traefik.http.routers.audiobookshelf.tls=true
      - traefik.http.routers.audiobookshelf.tls.certresolver=porkbun
      - traefik.http.routers.audiobookshelf.service=audiobookshelf
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    external: true
