services:
  mazanoke:
    container_name: mazanoke
    image: ghcr.io/civilblur/mazanoke:latest
    # ports:
    #   - "3474:80"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mazanoke.rule=Host(`{{{APP_DOMAIN}}}`)
      - traefik.http.routers.mazanoke.entrypoints=https
      - traefik.http.routers.mazanoke.tls=true
      - traefik.http.routers.mazanoke.tls.certresolver=porkbun
      - traefik.http.routers.mazanoke.service=mazanoke
      - traefik.http.services.mazanoke.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    external: true
