services:
  ytptube:
    user: 0:0
    image: ghcr.io/arabcoders/ytptube:v0.12.0@sha256:184f316a5716a32e63b4e3e8ba3bf34dd94f1fc866049dafd8e6a12f796870ac
    container_name: ytptube
    restart: unless-stopped
    # ports:
    #   - "8081:8081"
    volumes:
      - /docker/ytptube/config:/config:rw
      - /mnt/podcasts:/downloads:rw
    tmpfs:
      - /tmp
    labels:
      - traefik.enable=true
      - traefik.http.routers.ytptube.rule=Host(`{{{domainForApp "ytptube"}}}`)
      - traefik.http.routers.ytptube.entrypoints=https
      - traefik.http.routers.ytptube.tls=true
      - traefik.http.routers.ytptube.tls.certresolver=porkbun
      - traefik.http.routers.ytptube.service=ytptube
      - traefik.http.services.ytptube.loadbalancer.server.port=8081
    networks:
      - traefik

networks:
  traefik:
    external: true
