services:
  bentopdf:
    image: bentopdf/bentopdf:v1.11.2@sha256:5273e0ce98a3fb3eba735cf973712351a6c9593930114431db10b180c2c9b6cb
    container_name: bentopdf
    # ports:
    #   - "3000:8080"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bentopdf.rule=Host(`{{{domainForApp "bentopdf"}}}`)
      - traefik.http.routers.bentopdf.entrypoints=https
      - traefik.http.routers.bentopdf.tls=true
      - traefik.http.routers.bentopdf.tls.certresolver=porkbun
      - traefik.http.routers.bentopdf.service=bentopdf
      - traefik.http.services.bentopdf.loadbalancer.server.port=8080
    networks:
      - traefik

networks:
  traefik:
    external: true
