services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:2.6.0@sha256:96709a7ecd64a3fb4adf4dcf320808248a565993ea0c67febd25da12a34dcab7
    container_name: bentopdf
    # ports:
    #   - "3000:8080"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bentopdf.rule=Host(`{{{domainForApp "bentopdf"}}}`)
      - traefik.http.routers.bentopdf.entrypoints=https
      - traefik.http.routers.bentopdf.tls=true
      - traefik.http.routers.bentopdf.tls.certresolver=porkbun
      - traefik.http.routers.bentopdf.service=bentopdf
      - traefik.http.services.bentopdf.loadbalancer.server.port=8080
      - traefik.http.routers.bentopdf.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
