services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:2.5.0@sha256:c3729000f885059680cee9d49df50b21410cf80896be06f7e070de8f85a37816
    container_name: bentopdf
    # ports:
    #   - "3000:8080"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bentopdf.rule=Host(`{{{domainForApp "bentopdf"}}}`)
      - traefik.http.routers.bentopdf.entrypoints=https
      - traefik.http.routers.bentopdf.tls=true
      - traefik.http.routers.bentopdf.tls.certresolver=porkbun
      - traefik.http.routers.bentopdf.service=bentopdf
      - traefik.http.services.bentopdf.loadbalancer.server.port=8080
      - traefik.http.routers.bentopdf.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
