services:
  archiveteam:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile:latest@sha256:e8137b57f9ab9619e750b16afb375c203ec9da37389497790bcba28b1aaeabe3
    container_name: archiveteam-warrior
    # ports:
    #   - '8001:8001'
    # https://wiki.archiveteam.org/index.php/ArchiveTeam_Warrior/Docker_environment_variables
    environment:
      - DOWNLOADER=akmin
      - SELECTED_PROJECT=auto
      - CONCURRENT_ITEMS=6
    logging:
      options:
        max-size: 50m
      driver: json-file
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.archiveteamwarrior.rule=Host(`{{{domainForApp "archiveteam-warrior"}}}`)
      - traefik.http.routers.archiveteamwarrior.entrypoints=https
      - traefik.http.routers.archiveteamwarrior.tls=true
      - traefik.http.routers.archiveteamwarrior.tls.certresolver=porkbun
      - traefik.http.routers.archiveteamwarrior.service=archiveteamwarrior
      - traefik.http.services.archiveteamwarrior.loadbalancer.server.port=8001
      - traefik.http.routers.archiveteamwarrior.middlewares=oidc-auth@file
    networks:
      - traefik

networks:
  traefik:
    external: true
