# verified
id = 218
hostname = "downloader-pulumi"
enabled = false

description = "misc downloading tools"
stacks = ["traefik", "ytptube"]

[cpu]
cores = 1

[memory]
dedicated = 4096
swap = 2048

[disk]
size = 16

[[mountPoints]]
volume = "/void/podcasts"
mountPoint = "/mnt/podcasts"

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
