services:
  app:
    image: ghcr.io/itskovacs/trip:1.41.1@sha256:093681edf556e33def6b567a769cef05629b53c8f7e2c5c8d555b3f9fe815373
    # ports:
    #   - 127.0.0.1:8080:8000
    volumes:
      - /docker/trip:/app/storage
    command: ["fastapi", "run", "/app/trip/main.py", "--host", "0.0.0.0"]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.trip.rule=Host(`{{{domainForApp "trip"}}}`)
      - traefik.http.routers.trip.entrypoints=https
      - traefik.http.routers.trip.tls=true
      - traefik.http.routers.trip.tls.certresolver=porkbun
      - traefik.http.routers.trip.service=trip
      - traefik.http.services.trip.loadbalancer.server.port=8000
    networks:
      - traefik

networks:
  traefik:
    external: true
