services:
  app:
    image: ghcr.io/itskovacs/trip:1.38.0@sha256:c2aa28465226ff66f4a9a9fcaf994d9e5e4ed861f8f7bcbefedf97abdedf7fcc
    # ports:
    #   - 127.0.0.1:8080:8000
    volumes:
      - /docker/trip:/app/storage
    command: ["fastapi", "run", "/app/trip/main.py", "--host", "0.0.0.0"]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.trip.rule=Host(`{{{domainForApp "trip"}}}`)
      - traefik.http.routers.trip.entrypoints=https
      - traefik.http.routers.trip.tls=true
      - traefik.http.routers.trip.tls.certresolver=porkbun
      - traefik.http.routers.trip.service=trip
      - traefik.http.services.trip.loadbalancer.server.port=8000
    networks:
      - traefik

networks:
  traefik:
    external: true
