services:
  app:
    image: ghcr.io/itskovacs/trip:1.42.0@sha256:39bd625f85b83f88d5f5c1cade77a9d563dcf16acbd0290ac9416b92254f9ca8
    # ports:
    #   - 127.0.0.1:8080:8000
    volumes:
      - /docker/trip:/app/storage
    command: ["fastapi", "run", "/app/trip/main.py", "--host", "0.0.0.0"]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.trip.rule=Host(`{{{domainForApp "trip"}}}`)
      - traefik.http.routers.trip.entrypoints=https
      - traefik.http.routers.trip.tls=true
      - traefik.http.routers.trip.tls.certresolver=porkbun
      - traefik.http.routers.trip.service=trip
      - traefik.http.services.trip.loadbalancer.server.port=8000
    networks:
      - traefik

networks:
  traefik:
    external: true
