services:
  app:
    image: ghcr.io/itskovacs/trip:1.35.0@sha256:f2d38a44b499d12d7a513faac4cb1cc963cda4865e472cf06687006c20f026d5
    # ports:
    #   - 127.0.0.1:8080:8000
    volumes:
      - /docker/trip:/app/storage
    command: ["fastapi", "run", "/app/trip/main.py", "--host", "0.0.0.0"]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.trip.rule=Host(`{{{domainForApp "trip"}}}`)
      - traefik.http.routers.trip.entrypoints=https
      - traefik.http.routers.trip.tls=true
      - traefik.http.routers.trip.tls.certresolver=porkbun
      - traefik.http.routers.trip.service=trip
      - traefik.http.services.trip.loadbalancer.server.port=8000
    networks:
      - traefik

networks:
  traefik:
    external: true
