# verified
id = 206
hostname = "gitea-pulumi"
enabled = false

description = "lightweight private git server and github mirror"
stacks = ["traefik", "gitea"]

[cpu]
cores = 1

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 16

[[firewallRules]]
type = "in"
action = "ACCEPT"
dport = "222"
proto = "tcp"
comment = "gitea ssh"

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "ansible"
name = "gitea-setup"
playbook = "provisioners/ansible/gitea-setup.yaml"
replayable = true

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
