id = 206
hostname = "gitea-pulumi"
enabled = false

description = "lightweight private git server and github mirror"
services = ["traefik", "gitea"]

[cpu]
cores = 1

[memory]
dedicated = 2048
swap = 1024

[disk]
size = 16

[[provisioners]]
type = "ansible"
name = "lxc-init"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
name = "install-docker"
script = "provisioners/scripts/install-docker.sh"
