services:
  newt:
    image: fosrl/newt:1.11.0@sha256:ea9e2bc53850d4a8b2c6019d97172a2b3e3cb1a15412babb4a0f4adc522f4a79
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT={{{SECRET_PANGOLIN_ENDPOINT}}}
      - NEWT_ID={{{SECRET_NEWT_ID}}}
      - NEWT_SECRET={{{SECRET_NEWT_SECRET}}}
    networks:
      - traefik

networks:
  traefik:
    external: true
