services:
  newt:
    image: fosrl/newt:1.10.2@sha256:c7b4f508cba35d698a3e4b2d55e3d902ae993d6588198291ef8e232d30421974
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT={{{SECRET_PANGOLIN_ENDPOINT}}}
      - NEWT_ID={{{SECRET_NEWT_ID}}}
      - NEWT_SECRET={{{SECRET_NEWT_SECRET}}}
    networks:
      - traefik

networks:
  traefik:
    external: true
