services:
  newt:
    image: fosrl/newt:1.9.0@sha256:22edec551d81c500a9a3c790a41cd8f7eada3b47ba0a31a187c80d61318e4cc6
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT={{{SECRET_PANGOLIN_ENDPOINT}}}
      - NEWT_ID={{{SECRET_NEWT_ID}}}
      - NEWT_SECRET={{{SECRET_NEWT_SECRET}}}
    networks:
      - traefik

networks:
  traefik:
    external: true
